/**
 * Integration test: HarnessDaemon + GoalHarness lifecycle (ADR-001 Phase 3)
 *
 * Proves that HarnessDaemon picks up queued goals and processes them through
 * GoalHarness's elaborate→plan→delegate sequence, matching the AutonomyDaemon's
 * processQueuedGoals behaviour but routing execution through SchedulerCore.
 *
 * This test mirrors the daemon-knowledge-elaboration.integration.test.ts pattern
 * but uses the new GoalHarness architecture.
 */

import { GoalHarness } from '../../src/harness/goal-harness.js';
import { HarnessDaemon } from '../../src/harness/harness-daemon.js';
import type { IWorkOrderRepository } from '../../src/infra/persistence/repository-interface.js';
import type { IElaborationService, IPlanningService } from '../../src/app/lifecycle/stage-interfaces.js';
import type { ISchedulerCore } from '../../src/scheduler/core/types.js';
import type { Goal, WorkItem } from '../../src/work-order/types/index.js';

function makeGoal(overrides: Partial<Goal> = {}): Goal {
  return {
    id: 'goal-daemon-1',
    created_at: Date.now(),
    updated_at: Date.now(),
    title: 'Daemon Lifecycle Test Goal',
    description: 'A goal that should flow through the full harness lifecycle',
    success_criteria: [
      { description: 'Tests pass', type: 'deterministic', verification_method: 'npm test', required: true },
    ],
    status: 'queued',
    priority: 50,
    budget_tokens: 100000,
    spent_tokens: 0,
    spent_time_minutes: 0,
    spent_cost_usd: 0,
    ...overrides,
  };
}

function makeWorkItem(overrides: Partial<WorkItem> = {}): WorkItem {
  return {
    id: 'wi-daemon-1',
    created_at: Date.now(),
    updated_at: Date.now(),
    goal_id: 'goal-daemon-1',
    title: 'Planned Work Item',
    description: 'Generated by PlanningService',
    item_type: 'code',
    status: 'queued',
    priority: 1,
    effort_estimate: 'M',
    retry_count: 0,
    max_retries: 3,
    dependencies: [],
    verification_plan: [],
    ...overrides,
  } as WorkItem;
}

describe('HarnessDaemon + GoalHarness lifecycle (ADR-001 Phase 3)', () => {
  let repository: jest.Mocked<Pick<IWorkOrderRepository, 'createGoal' | 'getGoal' | 'updateGoalStatus' | 'listGoals' | 'initialize' | 'close'>>;
  let elaborationService: jest.Mocked<IElaborationService>;
  let planningService: jest.Mocked<IPlanningService>;
  let schedulerCore: jest.Mocked<Pick<ISchedulerCore, 'submitGoal' | 'cancelGoal'>>;
  let daemon: HarnessDaemon | null;

  beforeEach(() => {
    repository = {
      createGoal: jest.fn(),
      getGoal: jest.fn(),
      updateGoalStatus: jest.fn(),
      listGoals: jest.fn().mockReturnValue([]),
      initialize: jest.fn().mockResolvedValue(undefined),
      close: jest.fn(),
    };
    elaborationService = { elaborateGoal: jest.fn() };
    planningService = { planWorkItems: jest.fn() };
    schedulerCore = {
      submitGoal: jest.fn().mockResolvedValue(undefined),
      cancelGoal: jest.fn().mockResolvedValue(undefined),
    };
    daemon = null;
  });

  afterEach(() => {
    daemon?.stop();
  });

  it('picks up queued goals and processes through elaborate→plan→delegate', async () => {
    const goal = makeGoal({ id: 'queued-goal-1' });
    const workItems = [makeWorkItem({ id: 'wi-1', goal_id: 'queued-goal-1' })];

    // First poll returns one queued goal, subsequent polls return none
    repository.listGoals
      .mockReturnValueOnce([goal])
      .mockReturnValue([]);

    repository.getGoal.mockReturnValue(goal);

    elaborationService.elaborateGoal.mockResolvedValue({
      goal, clarifications: [], escalations: [],
    });
    planningService.planWorkItems.mockResolvedValue({
      workItems, dependencies: new Map(),
    });

    const goalHarness = new GoalHarness({
      repository: repository as unknown as IWorkOrderRepository,
      elaborationService,
      planningService,
      schedulerCore: schedulerCore as unknown as ISchedulerCore,
    });

    daemon = new HarnessDaemon(
      repository as unknown as IWorkOrderRepository,
      goalHarness,
      { pollingIntervalMs: 50, maxConcurrentGoals: 2 }
    );

    void daemon.start().catch(() => {});
    await new Promise((r) => setTimeout(r, 120));

    // Verify the full lifecycle ran
    expect(elaborationService.elaborateGoal).toHaveBeenCalledWith(goal);
    expect(planningService.planWorkItems).toHaveBeenCalledWith(goal);
    expect(repository.updateGoalStatus).toHaveBeenCalledWith('queued-goal-1', 'active');
    expect(schedulerCore.submitGoal).toHaveBeenCalledWith(goal);
  });

  it('blocks goals with escalations and does not delegate to scheduler', async () => {
    const goal = makeGoal({ id: 'escalated-goal' });

    repository.listGoals
      .mockReturnValueOnce([goal])
      .mockReturnValue([]);
    repository.getGoal.mockReturnValue(goal);

    elaborationService.elaborateGoal.mockResolvedValue({
      goal,
      clarifications: [],
      escalations: ['Missing required success criteria'],
    });

    const goalHarness = new GoalHarness({
      repository: repository as unknown as IWorkOrderRepository,
      elaborationService,
      planningService,
      schedulerCore: schedulerCore as unknown as ISchedulerCore,
    });

    daemon = new HarnessDaemon(
      repository as unknown as IWorkOrderRepository,
      goalHarness,
      { pollingIntervalMs: 50, maxConcurrentGoals: 2 }
    );

    void daemon.start().catch(() => {});
    await new Promise((r) => setTimeout(r, 120));

    expect(repository.updateGoalStatus).toHaveBeenCalledWith('escalated-goal', 'blocked');
    expect(planningService.planWorkItems).not.toHaveBeenCalled();
    expect(schedulerCore.submitGoal).not.toHaveBeenCalled();
  });

  it('processes multiple queued goals concurrently up to maxConcurrentGoals', async () => {
    const goals = [
      makeGoal({ id: 'g1' }),
      makeGoal({ id: 'g2' }),
      makeGoal({ id: 'g3' }),
    ];

    repository.listGoals.mockReturnValue(goals);
    repository.getGoal.mockImplementation((id) =>
      goals.find((goal) => goal.id === id)
    );

    // Make elaboration slow so goals stay "active" during the first cycle
    elaborationService.elaborateGoal.mockImplementation(async (g) => {
      await new Promise((r) => setTimeout(r, 300));
      return { goal: g, clarifications: [], escalations: [] };
    });
    planningService.planWorkItems.mockImplementation(async () => ({
      workItems: [makeWorkItem()], dependencies: new Map(),
    }));

    const goalHarness = new GoalHarness({
      repository: repository as unknown as IWorkOrderRepository,
      elaborationService,
      planningService,
      schedulerCore: schedulerCore as unknown as ISchedulerCore,
    });

    daemon = new HarnessDaemon(
      repository as unknown as IWorkOrderRepository,
      goalHarness,
      { pollingIntervalMs: 50, maxConcurrentGoals: 2 }
    );

    void daemon.start().catch(() => {});
    // Wait long enough for one cycle to start but not for elaboration to complete
    await new Promise((r) => setTimeout(r, 80));

    // Only 2 goals should have started processing (maxConcurrentGoals = 2)
    expect(elaborationService.elaborateGoal).toHaveBeenCalledTimes(2);
  });

  it('matches AutonomyDaemon capability: elaboration before planning', async () => {
    const goal = makeGoal({ id: 'sequence-check' });
    const callOrder: string[] = [];

    repository.listGoals
      .mockReturnValueOnce([goal])
      .mockReturnValue([]);
    repository.getGoal.mockReturnValue(goal);

    elaborationService.elaborateGoal.mockImplementation(async (g) => {
      callOrder.push('elaborate');
      return { goal: g, clarifications: [], escalations: [] };
    });
    planningService.planWorkItems.mockImplementation(async () => {
      callOrder.push('plan');
      return { workItems: [makeWorkItem()], dependencies: new Map() };
    });
    schedulerCore.submitGoal.mockImplementation(async () => {
      callOrder.push('delegate');
    });

    const goalHarness = new GoalHarness({
      repository: repository as unknown as IWorkOrderRepository,
      elaborationService,
      planningService,
      schedulerCore: schedulerCore as unknown as ISchedulerCore,
    });

    daemon = new HarnessDaemon(
      repository as unknown as IWorkOrderRepository,
      goalHarness,
      { pollingIntervalMs: 50, maxConcurrentGoals: 2 }
    );

    void daemon.start().catch(() => {});
    await new Promise((r) => setTimeout(r, 120));

    expect(callOrder).toEqual(['elaborate', 'plan', 'delegate']);
  });

  it('invariant: GlobalKnowledgeService injection path is exercised (via ElaborationService)', async () => {
    const goal = makeGoal({ id: 'knowledge-check' });

    repository.listGoals
      .mockReturnValueOnce([goal])
      .mockReturnValue([]);
    repository.getGoal.mockReturnValue(goal);

    // Simulate elaboration surfacing pitfalls from GlobalKnowledgeService
    elaborationService.elaborateGoal.mockResolvedValue({
      goal,
      clarifications: ['Pitfall: ensure DI wired in all paths'],
      escalations: [],
    });
    planningService.planWorkItems.mockResolvedValue({
      workItems: [makeWorkItem()], dependencies: new Map(),
    });

    const goalHarness = new GoalHarness({
      repository: repository as unknown as IWorkOrderRepository,
      elaborationService,
      planningService,
      schedulerCore: schedulerCore as unknown as ISchedulerCore,
    });

    daemon = new HarnessDaemon(
      repository as unknown as IWorkOrderRepository,
      goalHarness,
      { pollingIntervalMs: 50, maxConcurrentGoals: 2 }
    );

    void daemon.start().catch(() => {});
    await new Promise((r) => setTimeout(r, 120));

    // Goal should still proceed (clarifications don't block, only escalations do)
    expect(schedulerCore.submitGoal).toHaveBeenCalledWith(goal);
  });
});
