export const DeterministicRuntimeErrorCodes = {
  ERR_PLAN_SCHEMA_INVALID: 'ERR_PLAN_SCHEMA_INVALID',
  ERR_STEP_DEPENDENCY_INVALID: 'ERR_STEP_DEPENDENCY_INVALID',
  ERR_STEP_CYCLE_DETECTED: 'ERR_STEP_CYCLE_DETECTED',
  ERR_TOOL_NOT_FOUND: 'ERR_TOOL_NOT_FOUND',
  ERR_TOOL_ARGS_INVALID: 'ERR_TOOL_ARGS_INVALID',
  ERR_POLICY_DENIED: 'ERR_POLICY_DENIED',
  ERR_POLICY_REQUIRE_HUMAN_APPROVAL: 'ERR_POLICY_REQUIRE_HUMAN_APPROVAL',
  ERR_SCRIPT_SANDBOX_DENIED: 'ERR_SCRIPT_SANDBOX_DENIED',
  ERR_RUNTIME_STEP_TIMEOUT: 'ERR_RUNTIME_STEP_TIMEOUT',
  ERR_RUNTIME_TOOL_FAILED: 'ERR_RUNTIME_TOOL_FAILED',
  ERR_RUNTIME_INTERNAL: 'ERR_RUNTIME_INTERNAL',
} as const;

export type DeterministicRuntimeErrorCode =
  (typeof DeterministicRuntimeErrorCodes)[keyof typeof DeterministicRuntimeErrorCodes];
