/**
 * MessageWindow — token-aware message history with automatic compaction.
 *
 * The ReAct loop generates unbounded message arrays (20+ iterations with
 * large tool outputs). MessageWindow manages this by tracking estimated
 * token counts and compacting the middle portion of the history when
 * a threshold is exceeded. System prompts and the most recent messages
 * are always preserved.
 *
 * Part of ADR-002 Phase D2.
 */

import type { LLMMessage } from '../../infra/llm/llm-provider.js';
import type { ILLMService } from '../../infra/llm/llm-service.interface.js';
import type { ILogger } from '../../infra/observability/logger.js';

export interface MessageWindowConfig {
  maxTotalTokens: number;
  keepSystemPrompt: boolean;
  keepLastN: number;
  summarizeThreshold: number;
}

export const DEFAULT_MESSAGE_WINDOW_CONFIG: MessageWindowConfig = {
  maxTotalTokens: 80_000,
  keepSystemPrompt: true,
  keepLastN: 4,
  summarizeThreshold: 60_000,
};

export class MessageWindow {
  private messages: LLMMessage[] = [];
  private estimatedTokens = 0;
  private compacting = false;

  private readonly config: MessageWindowConfig;
  private readonly llmService: ILLMService;
  private readonly logger: ILogger;

  constructor(
    config: Partial<MessageWindowConfig>,
    llmService: ILLMService,
    logger: ILogger,
  ) {
    this.config = { ...DEFAULT_MESSAGE_WINDOW_CONFIG, ...config };
    this.llmService = llmService;
    this.logger = logger.child({ event: 'message-window' });
  }

  /**
   * Add a message to the window. Triggers compaction if the estimated
   * token count exceeds the summarize threshold.
   */
  async push(message: LLMMessage): Promise<void> {
    this.messages.push(message);
    this.estimatedTokens += this.estimateTokens(message);

    if (
      this.estimatedTokens >= this.config.summarizeThreshold &&
      !this.compacting
    ) {
      await this.compact();
    }
  }

  /**
   * Returns the current message array (defensive copy).
   */
  getMessages(): LLMMessage[] {
    return [...this.messages];
  }

  /**
   * Returns the current estimated token count.
   */
  getEstimatedTokens(): number {
    return this.estimatedTokens;
  }

  /**
   * Rough token estimate: content character length divided by 4.
   * Accounts for tool_calls JSON when present.
   */
  estimateTokens(message: LLMMessage): number {
    let charCount = 0;

    if (message.content) {
      charCount += message.content.length;
    }

    if (message.tool_calls) {
      for (const tc of message.tool_calls) {
        charCount += tc.function.name.length;
        charCount += tc.function.arguments.length;
      }
    }

    if (message.tool_call_id) {
      charCount += message.tool_call_id.length;
    }

    // Role and structural overhead: ~10 tokens baseline
    return Math.max(1, Math.ceil(charCount / 4) + 10);
  }

  /**
   * Compact the message history by summarizing the middle portion.
   *
   * Keeps:
   *   - System prompt (index 0 if role === 'system' and keepSystemPrompt)
   *   - Last N complete messages
   *
   * Replaces everything in between with a single summary message
   * generated by the LLM using the 'planning' workload.
   */
  private async compact(): Promise<void> {
    this.compacting = true;

    try {
      const { keepSystemPrompt, keepLastN } = this.config;

      // Determine the prefix (system prompt) boundary
      const hasSystemPrompt =
        keepSystemPrompt &&
        this.messages.length > 0 &&
        this.messages[0].role === 'system';

      const prefixEnd = hasSystemPrompt ? 1 : 0;

      // Determine the suffix (last N messages) boundary
      const suffixStart = Math.max(prefixEnd, this.messages.length - keepLastN);

      // If there is nothing in the middle to compact, bail out
      if (suffixStart <= prefixEnd) {
        this.logger.debug(
          {},
          `compact: nothing to summarize (prefix=${prefixEnd}, suffixStart=${suffixStart}, total=${this.messages.length})`,
        );
        return;
      }

      const middleMessages = this.messages.slice(prefixEnd, suffixStart);

      if (middleMessages.length === 0) {
        return;
      }

      this.logger.info(
        { middleCount: middleMessages.length, estimatedTokens: this.estimatedTokens },
        'compacting message window',
      );

      // Build a summarization request
      const summaryContent = middleMessages
        .map((m) => {
          const role = m.role;
          const content = m.content ?? '';
          const toolInfo = m.tool_calls
            ? ` [tool_calls: ${m.tool_calls.map((tc) => tc.function.name).join(', ')}]`
            : '';
          const toolId = m.tool_call_id ? ` [tool_call_id: ${m.tool_call_id}]` : '';
          return `[${role}]${toolInfo}${toolId}: ${content}`;
        })
        .join('\n');

      const summaryResponse = await this.llmService.complete('planning', [
        {
          role: 'system',
          content:
            'You are a conversation summarizer. Summarize the following conversation messages into a concise summary that preserves key decisions, tool results, and important context. Be brief but complete.',
        },
        {
          role: 'user',
          content: `Summarize these ${middleMessages.length} messages:\n\n${summaryContent}`,
        },
      ]);

      const summaryText =
        summaryResponse.content ?? '[Summary generation returned no content]';

      const summaryMessage: LLMMessage = {
        role: 'user',
        content: `[Conversation summary of ${middleMessages.length} earlier messages]:\n${summaryText}`,
      };

      // Reconstruct the message array
      const prefix = this.messages.slice(0, prefixEnd);
      const suffix = this.messages.slice(suffixStart);

      this.messages = [...prefix, summaryMessage, ...suffix];

      // Recalculate token estimate
      this.estimatedTokens = 0;
      for (const msg of this.messages) {
        this.estimatedTokens += this.estimateTokens(msg);
      }

      this.logger.info(
        {
          newMessageCount: this.messages.length,
          newEstimatedTokens: this.estimatedTokens,
        },
        'message window compacted',
      );
    } catch (err) {
      this.logger.error(
        {},
        'message window compaction failed, continuing with full history',
        err instanceof Error ? err : new Error(String(err)),
      );
    } finally {
      this.compacting = false;
    }
  }
}
